parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $dateFormat: 'Y-m-d H:i:s'

    App\:
        resource: '../Application'
        exclude:
            - '../Application/DependencyInjection/'
            - '../Application/Entity/'
            - '../Application/Kernel.php'

    App\UserInterface\API\Action\:
        resource: '../Application/UserInterface/API/Action'
        tags:
            - 'controller.service_arguments'

    App\UserInterface\Admin\Action\:
        resource: '../Application/UserInterface/Admin/Action'
        tags:
            - 'controller.service_arguments'
